# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest -n 2 --html=tests/report.html
  displayName: 'pytest'

- script: pip install -r requirements.txt
  displayName: 'Install requirements'
  
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    addToPath: true
    architecture: 'x64'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'tests/report.html'
    artifact: 'Test Reports'
    publishLocation: 'pipeline'
    
- task: PublishHtmlReport@1
  inputs:
    reportDir: 'tests/report.html'
